# Generated by Django 5.2.4 on 2025-08-06 14:44

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('sehir', models.CharField(max_length=20)),
                ('ilce', models.CharField(max_length=30)),
                ('ev_adres', models.TextField()),
                ('telefon_numarisi', models.CharField(max_length=10)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OdemeBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kart_numarisi', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('son_kullanma_tarihi', models.DateField()),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.adresbilgileri')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilYayinci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yayinci_ismi', models.CharField(max_length=100, unique=True)),
                ('yayinci_kodu', models.CharField(default=shop.models.yayinciKoduOlusturma, max_length=8, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KitapOlusturma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitap_ismi', models.CharField(max_length=100)),
                ('kitap_isbn', models.CharField(max_length=13, unique=True)),
                ('kitap_yazar_ismi', models.CharField(max_length=100)),
                ('kitap_acıklması', models.TextField(max_length=300)),
                ('kitap_fotografı', models.ImageField(blank=True, null=True, upload_to='')),
                ('yayınlama_yılı', models.DateField()),
                ('olusturulma_zamanı', models.DateTimeField(auto_now_add=True)),
                ('sayfa_sayısı', models.PositiveIntegerField()),
                ('kitap_turu', models.CharField(choices=[('ROMAN', 'Roman'), ('HİKAYE', 'Hikaye'), ('DENEME', 'deneme'), ('SİİR', 'Şiir'), ('BILIM', 'Bilim'), ('CIZGIROMAN', 'Çizgi roman'), ('EKONOMI', 'Ekonomi'), ('FELSEFE', 'Felsefe')], max_length=20)),
                ('kitap_fiyat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stok_adedi', models.IntegerField(default=0)),
                ('satısta_mı', models.BooleanField(default=True)),
                ('yayinci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.profilyayinci')),
            ],
        ),
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=1)),
                ('ekleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kitapolusturma')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
