# Generated by Django 5.2.4 on 2025-07-29 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitapOlusturma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitap_ismi', models.CharField(max_length=100)),
                ('kitap_yazar_ismi', models.CharField(max_length=100)),
                ('kitap_acıklması', models.TextField(max_length=300)),
                ('kitap_fotografı', models.ImageField(upload_to='')),
                ('yayınlama_yılı', models.DateField()),
                ('olusturulma_zamanı', models.DateTimeField(auto_now_add=True)),
                ('sayfa_sayısı', models.PositiveIntegerField()),
                ('kitap_turu', models.CharField(choices=[('ROMAN', 'Roman'), ('HİKAYE', 'Hikaye'), ('DENEME', 'deneme'), ('SİİR', 'Şiir'), ('BILIM', 'Bilim'), ('CIZGIROMAN', 'Çizgi roman'), ('EKONOMI', 'Ekonomi'), ('FELSEFE', 'Felsefe')], max_length=20)),
                ('kitap_fiyat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yayinci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
