# Generated by Django 5.2.4 on 2025-08-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OdemeBilgileri',
        ),
    ]
