# Generated by Django 5.2.4 on 2025-08-04 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_kitapolusturma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kitapolusturma',
            name='satısta_mı',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kitapolusturma',
            name='stok_adedi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kitapolusturma',
            name='kitap_fotografı',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='AdresBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('sehir', models.CharField(max_length=20)),
                ('ilce', models.CharField(max_length=30)),
                ('ev_adres', models.TextField()),
                ('telefon_numarisi', models.CharField(max_length=10)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OdemeBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kart_numarisi', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('son_kullanma_tarihi', models.DateField()),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.adresbilgileri')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=1)),
                ('ekleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kitapolusturma')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
