# Generated by Django 5.2.4 on 2025-08-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_odemebilgileri'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresbilgileri',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='adresbilgileri',
            name='kart_numarisi',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='adresbilgileri',
            name='son_kullanma_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
