# Generated by Django 5.2.4 on 2025-08-14 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_adresbilgileri_cvv_adresbilgileri_kart_numarisi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparisimler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_tarihi', models.DateTimeField(auto_now_add=True)),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.adresbilgileri')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiparisDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField(default=1)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kitapolusturma')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.siparisimler')),
            ],
        ),
    ]
