# Generated by Django 5.2.4 on 2025-08-15 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_siparisimler_siparisdetay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparisdetay',
            name='siparis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='shop.siparisimler'),
        ),
    ]
