# Generated by Django 5.2.4 on 2025-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_siparisdetay_siparis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitapolusturma',
            name='kitap_turu',
            field=models.CharField(choices=[('ROMAN', 'Roman'), ('HIKAYE', 'Hikaye'), ('DENEME', 'deneme'), ('SIIR', 'Şiir'), ('BILIM', 'Bilim'), ('CIZGI ROMAN', 'Çizgi roman'), ('EKONOMI', 'Ekonomi'), ('FELSEFE', 'Felsefe')], max_length=20),
        ),
    ]
